spring:
  datasource:
    url: jdbc:mysql://localhost:3306/study?
    username: root
    password: ghkd6016
    driver-class-name: com.mysql.cj.jdbc.Driver
---
mybatis:
  configuration.map-underscore-to-camel-case: true
  mapper-locations: mybatis-mapper/*.xml
  lazy-initialization: true
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

---
server:
  port : 8070